/**
 * Build-time codegen for swiftie-api.
 *
 * Reads validated data through `@swiftie-api/data` loaders (devDep, workspace:*)
 * and emits two kinds of TypeScript modules:
 *
 *   1. `src/__generated__/meta.ts` - eagerly bundled into `dist/index.js`:
 *      every album, every song WITHOUT lyrics, every quote, every era, plus
 *      lookup maps. Sync APIs read exclusively from this.
 *
 *   2. `src/__generated__/albums/<slug>.ts` (one per album) - each becomes a
 *      tsdown entry, so consumers can `import lover from 'swiftie-api/albums/lover'`
 *      and the main bundle can `await import('./albums/<slug>.js')`.
 *
 * The generated files contain only literal data + type imports - no zod, no
 * node:* references, no runtime dependency on `@swiftie-api/data`.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ALBUM_SLUGS,
  getAllAlbums,
  getAllQuotes,
  getEras,
  getSongsByAlbum,
  type Song,
} from '@swiftie-api/data';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, '..');
const defaultOutDir = join(packageRoot, 'src/__generated__');

const HEADER = `// AUTO-GENERATED by scripts/generate-bundled-data.ts. DO NOT EDIT.
// Regenerate via \`pnpm --filter swiftie-api gen\`
`;

export interface GenerateOptions {
  outDir?: string;
}

type SongMetaShape = Omit<Song, 'lyrics'>;

function stableStringify(value: unknown): string {
  return JSON.stringify(value, replaceWithSortedKeys(value), 2);
}

// JSON.stringify's `replacer` walks the object tree; we use it to enforce
// stable key ordering inside every plain object so codegen output is
// deterministic and diffs stay clean across runs.
function replaceWithSortedKeys(_root: unknown) {
  return (_key: string, value: unknown): unknown => {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
      return value;
    }
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort((a, b) =>
      a.localeCompare(b),
    )) {
      sorted[key] = (value as Record<string, unknown>)[key];
    }
    return sorted;
  };
}

function stripLyrics<T extends { lyrics?: unknown }>(song: T): Omit<T, 'lyrics'> {
  const { lyrics: _omit, ...rest } = song;
  return rest;
}

async function writeMeta(outDir: string): Promise<void> {
  const [albums, quotes, eras] = await Promise.all([getAllAlbums(), getAllQuotes(), getEras()]);

  const songLists = await Promise.all(ALBUM_SLUGS.map((slug) => getSongsByAlbum(slug)));
  const songsMeta: SongMetaShape[] = songLists.flat().map(stripLyrics);

  const sortedAlbums = [...albums].sort((a, b) => a.slug.localeCompare(b.slug));
  const sortedQuotes = [...quotes].sort((a, b) => a.id.localeCompare(b.id));
  const sortedEras = [...eras].sort((a, b) => a.startDate.localeCompare(b.startDate));
  const sortedSongs = songsMeta.toSorted((a, b) => a.slug.localeCompare(b.slug));

  const contents = `${HEADER}
import type { Album, AlbumSlug, Era, Quote, SongMeta } from '../shared/types.js';

export const ALBUM_SLUGS = ${stableStringify(ALBUM_SLUGS)} as const satisfies readonly AlbumSlug[];

export const ALBUMS: readonly Album[] = ${stableStringify(sortedAlbums)};

export const ALBUM_BY_SLUG: ReadonlyMap<string, Album> = new Map(
  ALBUMS.map((album) => [album.slug, album]),
);

export const SONGS_META: readonly SongMeta[] = ${stableStringify(sortedSongs)};

export const SONGS_META_BY_SLUG: ReadonlyMap<string, SongMeta> = new Map(
  SONGS_META.map((song) => [song.slug, song]),
);

export const QUOTES: readonly Quote[] = ${stableStringify(sortedQuotes)};

export const ERAS: readonly Era[] = ${stableStringify(sortedEras)};
`;

  await writeFile(join(outDir, 'meta.ts'), contents, 'utf8');
}

async function writeAlbumModules(outDir: string): Promise<void> {
  const albumsDir = join(outDir, 'albums');
  await rm(albumsDir, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 });
  await mkdir(albumsDir, { recursive: true });

  const albums = await getAllAlbums();
  const albumBySlug = new Map(albums.map((a) => [a.slug, a]));

  await Promise.all(
    ALBUM_SLUGS.map(async (slug) => {
      const album = albumBySlug.get(slug);
      if (!album) {
        throw new Error(`Codegen: no album found for slug "${slug}".`);
      }
      const songs = await getSongsByAlbum(slug);
      const sortedSongs = [...songs].sort(
        (a, b) => a.discNumber - b.discNumber || a.trackNumber - b.trackNumber,
      );
      const payload = { ...album, songs: sortedSongs };
      const contents = `${HEADER}
import type { AlbumWithSongs } from '../../shared/types.js';

const data: AlbumWithSongs = ${stableStringify(payload)};

export default data;
`;
      await writeFile(join(albumsDir, `${slug}.ts`), contents, 'utf8');
    }),
  );
}

export async function generateBundledData(options: GenerateOptions = {}): Promise<void> {
  const outDir = options.outDir ? join(packageRoot, options.outDir) : defaultOutDir;
  await mkdir(outDir, { recursive: true });
  await Promise.all([writeMeta(outDir), writeAlbumModules(outDir)]);
}

const isDirectInvocation = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isDirectInvocation) {
  generateBundledData().then(
    () => {
      console.log(`Generated bundled data into ${defaultOutDir}`);
    },
    (err: unknown) => {
      console.error(err);
      process.exit(1);
    },
  );
}
